import { createContext, useState, useContext } from "react";

export const GamelogContext = createContext();

const exampleID = "paulch01";
const exampleGamelog = [
  {
    date_game: "2022-10-19",
    team_id: "PHO",
    opp_id: "DAL",
    game_result: "W (+2)",
    gs: "1",
    mp: "30:17",
    fg: "1",
    fga: "6",
    fg_pct: ".167",
    fg3: "0",
    fg3a: "2",
    fg3_pct: ".000",
    ft: "4",
    fta: "4",
    ft_pct: "1.000",
    orb: "0",
    drb: "3",
    trb: "3",
    ast: "9",
    stl: "2",
    blk: "0",
    tov: "3",
    pf: "3",
    pts: "6",
    game_score: "7.2",
    plus_minus: "-9",
  },
  {
    date_game: "2022-10-21",
    team_id: "PHO",
    game_location: "@",
    opp_id: "POR",
    game_result: "L (-2)",
    gs: "1",
    mp: "36:09",
    fg: "5",
    fga: "11",
    fg_pct: ".455",
    fg3: "0",
    fg3a: "1",
    fg3_pct: ".000",
    ft: "0",
    fta: "0",
    orb: "0",
    drb: "4",
    trb: "4",
    ast: "12",
    stl: "5",
    blk: "0",
    tov: "1",
    pf: "5",
    pts: "10",
    game_score: "15.9",
    plus_minus: "0",
  },
  {
    date_game: "2022-10-23",
    team_id: "PHO",
    game_location: "@",
    opp_id: "LAC",
    game_result: "W (+17)",
    gs: "1",
    mp: "32:37",
    fg: "3",
    fga: "11",
    fg_pct: ".273",
    fg3: "1",
    fg3a: "8",
    fg3_pct: ".125",
    ft: "0",
    fta: "0",
    orb: "3",
    drb: "5",
    trb: "8",
    ast: "11",
    stl: "1",
    blk: "1",
    tov: "2",
    pf: "2",
    pts: "7",
    game_score: "10.7",
    plus_minus: "+15",
  },
  {
    date_game: "2022-10-25",
    team_id: "PHO",
    opp_id: "GSW",
    game_result: "W (+29)",
    gs: "1",
    mp: "35:13",
    fg: "5",
    fga: "10",
    fg_pct: ".500",
    fg3: "4",
    fg3a: "5",
    fg3_pct: ".800",
    ft: "2",
    fta: "2",
    ft_pct: "1.000",
    orb: "0",
    drb: "7",
    trb: "7",
    ast: "9",
    stl: "1",
    blk: "0",
    tov: "2",
    pf: "4",
    pts: "16",
    game_score: "16.8",
    plus_minus: "+21",
  },
  {
    date_game: "2022-10-28",
    team_id: "PHO",
    opp_id: "NOP",
    game_result: "W (+13)",
    gs: "1",
    mp: "30:38",
    fg: "1",
    fga: "7",
    fg_pct: ".143",
    fg3: "0",
    fg3a: "1",
    fg3_pct: ".000",
    ft: "5",
    fta: "6",
    ft_pct: ".833",
    orb: "1",
    drb: "4",
    trb: "5",
    ast: "9",
    stl: "1",
    blk: "0",
    tov: "3",
    pf: "1",
    pts: "7",
    game_score: "7.9",
    plus_minus: "-3",
  },
  {
    date_game: "2022-10-30",
    team_id: "PHO",
    opp_id: "HOU",
    game_result: "W (+15)",
    gs: "1",
    mp: "31:14",
    fg: "3",
    fga: "7",
    fg_pct: ".429",
    fg3: "0",
    fg3a: "4",
    fg3_pct: ".000",
    ft: "4",
    fta: "5",
    ft_pct: ".800",
    orb: "0",
    drb: "1",
    trb: "1",
    ast: "15",
    stl: "0",
    blk: "0",
    tov: "0",
    pf: "1",
    pts: "10",
    game_score: "16.3",
    plus_minus: "+19",
  },
  {
    date_game: "2022-11-01",
    team_id: "PHO",
    opp_id: "MIN",
    game_result: "W (+9)",
    gs: "1",
    mp: "33:52",
    fg: "5",
    fga: "12",
    fg_pct: ".417",
    fg3: "1",
    fg3a: "5",
    fg3_pct: ".200",
    ft: "4",
    fta: "6",
    ft_pct: ".667",
    orb: "1",
    drb: "7",
    trb: "8",
    ast: "12",
    stl: "3",
    blk: "0",
    tov: "1",
    pf: "2",
    pts: "15",
    game_score: "20.2",
    plus_minus: "+18",
  },
  {
    date_game: "2022-11-04",
    team_id: "PHO",
    opp_id: "POR",
    game_result: "L (-2)",
    gs: "1",
    mp: "33:48",
    fg: "1",
    fga: "4",
    fg_pct: ".250",
    fg3: "1",
    fg3a: "3",
    fg3_pct: ".333",
    ft: "4",
    fta: "4",
    ft_pct: "1.000",
    orb: "0",
    drb: "2",
    trb: "2",
    ast: "11",
    stl: "2",
    blk: "1",
    tov: "0",
    pf: "2",
    pts: "7",
    game_score: "14.8",
    plus_minus: "+4",
  },
  {
    date_game: "2022-11-05",
    team_id: "PHO",
    opp_id: "POR",
    game_result: "W (+20)",
    gs: "1",
    mp: "24:21",
    fg: "3",
    fga: "7",
    fg_pct: ".429",
    fg3: "2",
    fg3a: "4",
    fg3_pct: ".500",
    ft: "7",
    fta: "7",
    ft_pct: "1.000",
    orb: "0",
    drb: "5",
    trb: "5",
    ast: "4",
    stl: "0",
    blk: "0",
    tov: "1",
    pf: "2",
    pts: "15",
    game_score: "13.8",
    plus_minus: "+16",
  },
  {
    date_game: "2022-11-07",
    team_id: "PHO",
    game_location: "@",
    opp_id: "PHI",
    game_result: "L (-12)",
    gs: "1",
    mp: "13:45",
    fg: "1",
    fga: "1",
    fg_pct: "1.000",
    fg3: "0",
    fg3a: "0",
    ft: "0",
    fta: "0",
    orb: "0",
    drb: "2",
    trb: "2",
    ast: "2",
    stl: "2",
    blk: "0",
    tov: "2",
    pf: "1",
    pts: "2",
    game_score: "3.3",
    plus_minus: "-10",
  },
  {
    date_game: "2022-11-09",
    team_id: "PHO",
    game_location: "@",
    opp_id: "MIN",
    game_result: "W (+12)",
    reason: "Did Not Dress",
  },
  {
    date_game: "2022-11-11",
    team_id: "PHO",
    game_location: "@",
    opp_id: "ORL",
    game_result: "L (-17)",
    reason: "Did Not Dress",
  },
  {
    date_game: "2022-11-14",
    team_id: "PHO",
    game_location: "@",
    opp_id: "MIA",
    game_result: "L (-1)",
    reason: "Did Not Dress",
  },
];

const eaxmpleColums = [
  "date_game",
  "team_id",
  "opp_id",
  "game_result",
  "gs",
  "mp",
  "fg",
  "fga",
  "fg_pct",
  "fg3",
  "fg3a",
  "fg3_pct",
  "ft",
  "fta",
  "ft_pct",
  "orb",
  "drb",
  "trb",
  "ast",
  "stl",
  "blk",
  "tov",
  "pf",
  "pts",
  "game_score",
  "plus_minus",
];

export const GamelogContextProvider = ({ children }) => {
  const [PlayerGamelogs, setPlayerGamelogs] = useState({
    [exampleID]: exampleGamelog,
  });
  const [GamelogColumns, setGamelogColumns] = useState(eaxmpleColums);

  return (
    <GamelogContext.Provider
      value={{
        PlayerGamelogs,
        setPlayerGamelogs,
        GamelogColumns,
        setGamelogColumns,
      }}
    >
      {children}
    </GamelogContext.Provider>
  );
};

export const useGamelogData = () => {
  const {
    PlayerGamelogs,
    setPlayerGamelogs,
    GamelogColumns,
    setGamelogColumns,
  } = useContext(GamelogContext);

  const getPlayerGamelog = (playerId) => {
    if (PlayerGamelogs.hasOwnProperty(playerId)) {
      return PlayerGamelogs[playerId];
    }
    return false;
  };

  const addPlayerGamelog = (playerId, gamelog) => {
    setPlayerGamelogs({ ...PlayerGamelogs, [playerId]: gamelog });
  };

  return {
    getPlayerGamelog,
    addPlayerGamelog,
    GamelogColumns,
    setGamelogColumns,
  };
};
